database:
  url: jdbc:postgresql://localhost:5432/artemaverkov
  username: artemaverkov
  password: root
  driver-class-name: org.postgresql.Driver
  createSchema: true
  insertSchema: true
cache:
  max-size: 100
  algorithm: LRU


